name: news_app
description: A new Flutter project with clean architecture.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # icons
  ionicons: ^0.2.2
  # bloc
  flutter_bloc: ^8.1.3
  # comparing objects
  equatable: ^2.0.5
  # generate code
  freezed_annotation: ^2.4.1
  # service locator
  get_it: ^7.6.0
  # format strings
  intl: ^0.18.1
  # local db
  floor: ^1.4.2
  # api call
  retrofit: ^4.0.1
  # hooks
  flutter_hooks: ^0.20.0
  # network image
  cached_network_image: ^3.2.3
  # fonts
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  retrofit_generator: ^7.0.8
  floor_generator: ^1.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

